name: Fork Sync develop branch with parent repository

on:
    schedule:
        - cron: "5 0 * * *" # Runs at 00:05
    workflow_dispatch: # on button click

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - uses: tgymnich/fork-sync@v1.8
              with:
                  base: develop
                  head: main
                  pr_title: Fork Sync develop branch with parent repository
