name: Fork Sync develop branch with parent repository

on:
    schedule:
        - cron: "15 * * * *" # runs every hour
    workflow_dispatch: # on button click

jobs:
    check-for-changes:
        runs-on: ubuntu-latest

        steps:
            - name: Check for changes
              id: changes
              run: |
                  chmod +x fork-sync-check-for-changes.sh # Make the script executable
                  ./fork-sync-check-for-changes.sh develop main # Pass branch names as parameters

    sync:
        needs: check-for-changes
        runs-on: ubuntu-latest
        if: needs.check-for-changes.outputs.changes == 'true'

        steps:
            - uses: tgymnich/fork-sync@v1.8
              with:
                  base: develop
                  head: main
                  pr_title: Fork Sync develop branch with parent repository
