name: Sync fork branches with parent repository

on:
    schedule:
        - cron: "0 */3 * * *"
    workflow_dispatch: # on button click

env:
    textreplace-changes: false
    messagelogger-changes: false
    develop-changes: false
    main-changes: false

jobs:
    check-for-changes:
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v4
            - name: Check for changes in branch
              id: check-changes
              run: |
                  if ! git remote | grep -q "upstream"; then
                      git remote add upstream https://github.com/Vendicated/Vencord
                      echo "Added upstream remote"
                  else
                      echo "The upstream remote already exists"
                  fi

                  function check_changes() {
                      local fork_branch="$1"
                      local upstream_branch="$2"
                      git fetch origin "$fork_branch:origin_$fork_branch"
                      git fetch upstream "$upstream_branch:upstream_$upstream_branch"
                      CHANGES=$(git log --oneline "origin_$fork_branch..upstream_$upstream_branch")
                      echo "Changes: $CHANGES"
                      if [ -n "$CHANGES" ]; then
                          echo "$fork_branch-changes=true"
                          echo "$fork_branch-changes=true" >> "$GITHUB_OUTPUT"
                      else
                          echo "$fork_branch-changes=false"
                          echo "$fork_branch-changes=false" >> "$GITHUB_OUTPUT"
                      fi
                  }
                  check_changes "textreplace" "main"
                  check_changes "messagelogger" "main"
                  check_changes "develop" "main"
                  check_changes "main" "main"

        outputs:
            textreplace-changes: ${{ steps.check-changes.outputs.textreplace-changes }}
            messagelogger-changes: ${{ steps.check-changes.outputs.messagelogger-changes }}
            develop-changes: ${{ steps.check-changes.outputs.develop-changes }}
            main-changes: ${{ steps.check-changes.outputs.main-changes }}

    sync:
        needs: check-for-changes
        runs-on: ubuntu-latest

        steps:
            #- name: Sync TextReplace branch with parent repository
            #  if: ${{ needs.check-for-changes.outputs.textreplace-changes == 'true' }}
            #  uses: tgymnich/fork-sync@v1.8
            #  continue-on-error: true
            #  with:
            #      base: textreplace
            #      head: main
            #      pr_title: Sync TextReplace branch with parent repository
            #- name: Sync MessageLogger branch with parent repository
            #  if: ${{ needs.check-for-changes.outputs.messagelogger-changes == 'true' }}
            #  uses: tgymnich/fork-sync@v1.8
            #  continue-on-error: true
            #  with:
            #      base: messagelogger
            #      head: main
            #      pr_title: Sync MessageLogger branch with parent repository
            #- name: Sync develop branch with parent repository
            #  if: ${{ needs.check-for-changes.outputs.develop-changes == 'true' }}
            #  uses: tgymnich/fork-sync@v1.8
            #  continue-on-error: true
            #  with:
            #      base: develop
            #      head: main
            #      pr_title: Sync develop branch with parent repository
            - name: Sync main branch with parent repository
              if: ${{ needs.check-for-changes.outputs.main-changes == 'true' }}
              run: gh repo sync HeLau1337/Vencord -b main
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
