name: Sync Fork

on:
    schedule:
        - cron: "0 0 * * *" # Runs at 00:00
    workflow_dispatch: # on button click

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - uses: tgymnich/fork-sync@v1.8
              with:
                  token: ${{ secrets.PERSONAL_TOKEN }}
                  base: main
                  head: develop
