name: Fork Sync main branch with parent repository

on:
    schedule:
        - cron: "0 0 * * *" # Runs at 00:00
    workflow_dispatch: # on button click

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - run: gh repo sync HeLau1337/Vencord -b main

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
