name: Fork Sync TextReplace branch with parent repository

on:
    schedule:
        - cron: "15 * * * *" # runs every hour
    workflow_dispatch: # on button click

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - uses: tgymnich/fork-sync@v1.8
              with:
                  base: textreplace-rules-in-settings-json
                  head: main
                  pr_title: Fork Sync TextReplace branch with parent repository
